In [39]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [40]:
df = pd.read_csv('music_streaming_habits_2026.csv')

In [41]:
df

,listener_id,age,country,platform,subscription,top_genre,top_artist,daily_listening_minutes,songs_per_day,playlists_count,skip_rate_pct,discover_weekly_user,top_mood,uses_offline_mode,podcasts_too
0,1,24,Australia,Apple Music,Free,R&B,Kendrick Lamar,191,54,9,39.3,False,Sleep,False,True
1,2,21,Germany,Spotify,Free,Classical,Drake,249,68,10,18.3,True,Workout,True,True
2,3,32,Japan,Amazon Music,Free,Hip-Hop,Olivia Rodrigo,49,11,11,22.7,True,Sad,False,True
3,4,39,Japan,Apple Music,Free,Pop,Burna Boy,96,22,8,29.4,True,Sad,True,False
4,5,23,India,Spotify,Family,Country,Olivia Rodrigo,100,24,13,37.7,True,Workout,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,3996,26,France,Spotify,Family,Pop,SZA,197,55,6,15.3,False,Workout,True,False
3996,3997,35,Germany,YouTube Music,Free,Rock,Ariana Grande,320,77,13,9.2,True,Sad,False,True
3997,3998,43,India,Apple Music,Free,Hip-Hop,Dua Lipa,99,38,5,14.0,False,Happy,True,True
3998,3999,26,India,Apple Music,Student,Indie,SZA,76,31,7,36.1,False,Happy,False,False
3999,4000,24,UK,Spotify,Premium,Hip-Hop,Dua Lipa,161,49,9,37.8,True,Workout,False,False

In [42]:
df.head()

,listener_id,age,country,platform,subscription,top_genre,top_artist,daily_listening_minutes,songs_per_day,playlists_count,skip_rate_pct,discover_weekly_user,top_mood,uses_offline_mode,podcasts_too
0,1,24,Australia,Apple Music,Free,R&B,Kendrick Lamar,191,54,9,39.3,False,Sleep,False,True
1,2,21,Germany,Spotify,Free,Classical,Drake,249,68,10,18.3,True,Workout,True,True
2,3,32,Japan,Amazon Music,Free,Hip-Hop,Olivia Rodrigo,49,11,11,22.7,True,Sad,False,True
3,4,39,Japan,Apple Music,Free,Pop,Burna Boy,96,22,8,29.4,True,Sad,True,False
4,5,23,India,Spotify,Family,Country,Olivia Rodrigo,100,24,13,37.7,True,Workout,True,True

In [43]:
df1 = df

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   listener_id              4000 non-null   int64
 1   age                      4000 non-null   int64
 2   country                  4000 non-null   object
 3   platform                 4000 non-null   object
 4   subscription             4000 non-null   object
 5   top_genre                4000 non-null   object
 6   top_artist               4000 non-null   object
 7   daily_listening_minutes  4000 non-null   int64
 8   songs_per_day            4000 non-null   int64
 9   playlists_count          4000 non-null   int64
 10  skip_rate_pct            4000 non-null   float64
 11  discover_weekly_user     4000 non-null   bool
 12  top_mood                 4000 non-null   object
 13  uses_offline_mode        4000 non-null   bool
 14  podcasts_too             4000 non-null   bool
dtypes: bool(3), float64(1), int64(5), object(6)
memory usage: 386.8+ KB

In [45]:
df.describe()

,listener_id,age,daily_listening_minutes,songs_per_day,playlists_count,skip_rate_pct
count,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000
mean,2000.500000,27.849000,138.702750,39.137500,8.994500,28.163375
std,1154.844867,8.595881,86.296023,25.046296,3.027914,11.815850
min,1.000000,13.000000,5.000000,1.000000,1.000000,0.000000
25%,1000.750000,22.000000,74.000000,21.000000,7.000000,20.000000
50%,2000.500000,28.000000,122.000000,35.000000,9.000000,28.100000
75%,3000.250000,34.000000,185.000000,52.250000,11.000000,36.300000
max,4000.000000,57.000000,697.000000,198.000000,22.000000,70.900000

In [46]:
df.duplicated().sum()

0

In [47]:
df.value_counts()

listener_id  age  country    platform       subscription  top_genre  top_artist         daily_listening_minutes  songs_per_day  playlists_count  skip_rate_pct  discover_weekly_user  top_mood   uses_offline_mode  podcasts_too
1            24   Australia  Apple Music    Free          R&B        Kendrick Lamar     191                      54             9                39.3           False                 Sleep      False              True            1
2672         18   Australia  YouTube Music  Family        Rock       Olivia Rodrigo     64                       29             7                11.3           False                 Workout    True               False           1
2659         32   Japan      Spotify        Student       Hip-Hop    Tyler the Creator  29                       4              7                25.7           False                 Workout    True               False           1
2660         21   USA        SoundCloud     Premium       Classical  Dua Lipa           59                       23             13               21.8           False                 Sleep      True               False           1
2661         26   India      Spotify        Free          Lo-fi      SZA                48                       7              5                39.6           False                 Party      False              False           1
                                                                                                                                                                                                                                   ..
1339         41   India      Apple Music    Free          Pop        Tyler the Creator  50                       6              5                13.9           False                 Energetic  True               True            1
1340         24   Australia  Spotify        Student       Country    Taylor Swift       179                      48             10               24.4           True                  Happy      False              False           1
1341         27   Japan      Amazon Music   Family        Afrobeats  Bad Bunny          94                       33             15               32.4           False                 Happy      True               False           1
1342         27   Canada     Spotify        Student       EDM        Burna Boy          271                      71             7                19.4           False                 Sad        True               True            1
4000         24   UK         Spotify        Premium       Hip-Hop    Dua Lipa           161                      49             9                37.8           True                  Workout    False              False           1
Name: count, Length: 4000, dtype: int64

In [48]:
df['country'].value_counts()

country
Japan        439
Canada       429
USA          418
Brazil       409
Nigeria      401
Australia    397
India        390
France       377
Germany      371
UK           369
Name: count, dtype: int64

In [49]:
df['platform'].unique()

array(['Apple Music', 'Spotify', 'Amazon Music', 'Tidal', 'SoundCloud',
       'YouTube Music'], dtype=object)

In [50]:
for i in df.columns:
    print(f"{i}: {df[i].unique()} unique values \n")

listener_id: [   1    2    3 ... 3998 3999 4000] unique values

age: [24 21 32 39 23 41 13 22 40 27 31 30 50 28 37 20 15 26 38 34 25 16 17 35
 14 42 43 44 29 33 19 18 36 48 47 45 56 46 49 52 51 53 55 57] unique values

country: ['Australia' 'Germany' 'Japan' 'India' 'Nigeria' 'Canada' 'USA' 'UK'
 'Brazil' 'France'] unique values

platform: ['Apple Music' 'Spotify' 'Amazon Music' 'Tidal' 'SoundCloud'
 'YouTube Music'] unique values

subscription: ['Free' 'Family' 'Premium' 'Student'] unique values

top_genre: ['R&B' 'Classical' 'Hip-Hop' 'Pop' 'Country' 'Rock' 'EDM' 'Jazz' 'Lo-fi'
 'K-Pop' 'Afrobeats' 'Indie'] unique values

top_artist: ['Kendrick Lamar' 'Drake' 'Olivia Rodrigo' 'Burna Boy' 'Bad Bunny' 'SZA'
 'Taylor Swift' 'Travis Scott' 'Billie Eilish' 'The Weeknd' 'BTS'
 'Dua Lipa' 'Tyler the Creator' 'Ariana Grande'] unique values

daily_listening_minutes: [191 249  49  96 100  64 193 142 120 127 255 481 330 107  54  75 288  39
  58 121 222 140 171 212  41  50  45  40  25 134 225 214 270 170 233 129
 112 155 256  88 154  17  80 282 123 141 182  77  99 156  60  89 267 145
 118  63 151 208  62  53  91 217 131 115 254 245  79 240  73 190  36 106
  55  76 226  72  98 130 103 132  16 181 133  57 109 374 265  37  74 144
   6 108 176 228  70 164 146 323  28 149 277 180  69 105 204 257  85 246
 162  92 302 174 122 113  84 209 173 355 194  56 535  52  20 172 124 248
 119  61 230 297 169 319 192 117 160 159  42  35 167 263 116 139 200 281
 422 189 232 128 185 234 110  71  26 148  78 135  86  43 102 168  83 199
 166 307 284  46 250 125 153 380 137 309  44  97  29 111  18  90 279  51
 202 186 206 138 278 326 157 152  32 301  93 220   9  24 183  67 292 210
 260  95 317 213 205 337 269   7 177  33 114  66 126  68 253 293 207 227
  81 143  27  87 290  38 196 318 104  30 274  23  48 360 224 241 268 252
 218 346  82 147 101  31 197  34 163 295 375  15 287  59 187 223 161 179
 243 215 373 403 198 216 304 175  47 310 559 271   8 219 286 372 450 321
 150 258 452 247 283 231 165 393 386 462  14 390 343 358  11 264 184 201
  94 289 229 329 311 366 423 547 376   5 320 480 453 357  22 445 548 237
 266  65 273 351 239  21 261 340 377 440 195 203 296 251 188 136 272  10
 259 474 158 395 501 369 275  13 414 314 221 235 178 378 397 303 313 345
 341 396 382 697 384 276 427 324 325 236 332 285 454 411  19 322 211 238
 464 394 626 300 298 299 371 262 359 280 305 334 447  12 370 244 389 242
 392 308 348 356 466 352 294 342 331 291 381 387 379 413 418 335 338 315
 441 336 409 333 306 347 406 577 436 430 448 354 353] unique values

songs_per_day: [ 54  68  11  22  24  19  53  44  38  33  73 135  97  36  15  18  81   9
  59  58  62  13  17  31   4  39  75  61  78  63  43  32  28  41   1  84
  49  48  21  35  30  72  23  42  65  66  77  64  47  34  10  12  27   3
  57 104  79   7  20  46  60  40 101  90  50  29  69  74   8  51  25  92
  52 100  26 159  88  55 118   6  45  16  14  37  85  76 108  93  67  80
  70   2  87  83  56   5 109  99 110 117  86  94 162 112 130 129  71  91
 123 154  82  95 139 128 160  98 122 136 148 113 115 111 102 103 119 198
 121 106 114 131 116 107 134 179  96  89 105 141 171 125] unique values

playlists_count: [ 9 10 11  8 13  7  5 12 14  4  6 16  3 15 18  2 17 22 19  1 20 21] unique values

skip_rate_pct: [39.3 18.3 22.7 29.4 37.7 12.  20.3 33.3 15.4 48.7 42.2 35.8 21.7 24.9
 10.  37.9 25.5 31.8 42.9 16.4  7.3 34.3 25.  21.4 21.9 41.  44.8 36.9
 15.7 13.2 38.8  7.  29.7 12.4 40.9 13.6 10.9 54.3 26.2 39.2 36.6  0.
 23.2 32.2 44.4  5.4 23.9 43.2 19.9 15.6 40.8 32.5 27.2 39.1 40.  20.2
 34.1 32.6 15.3 27.7 21.3 23.1  4.9 19.5 21.1 35.4 43.8 35.9 24.4 13.8
 32.1 39.6 12.1 22.  42.8 29.5 23.4 28.1 20.9 26.1 30.9 31.5 47.5 30.3
  1.6 23.8 39.5 31.3 19.7 24.  24.7 31.1 34.9 21.  48.9  7.6 23.7 47.6
 37.6 26.6 25.4 25.9  6.8 33.4 33.6 38.9 27.6 18.4 44.5 16.2 30.2 27.
 33.  61.9 16.8 36.4 31.9 31.2 19.3 23.6 36.2 28.9 20.5 43.6 24.5 17.3
 55.  23.5 41.7 41.2 29.1  8.5 13.1 41.9 43.5 60.3 26.5 11.6 22.6 35.3
 15.2 19.8 37.2 28.7 27.4 15.1 29.3 45.7  4.8 20.6 18.8 14.7 16.6 35.6
 38.4 42.3 11.5  5.6 27.9 30.6 50.4 41.1 34.7 25.7 29.8 35.  46.8 43.3
 33.7 40.5 20.8 33.5 10.1 14.5 32.8 39.7 10.3 28.6 44.2 33.9 22.4 28.2
 35.2 19.1 54.5 20.7 13.5 23.3  8.7 21.6 38.7 19.  30.4 17.4 31.6 38.6
 36.8 48.6 26.  22.5 30.7 35.1 32.7 62.4 67.8 18.7 30.8 17.  41.5 24.8
 36.5 25.1  5.9 47.3 41.4 40.2 10.7 48.  34.4 26.7 50.7  4.6 11.2  0.5
 14.9 52.4  1.1  9.3 36.7 19.4 18.  14.1 30.1 29.  26.4 21.5 26.8 16.3
 13.  37.5 33.1 12.6 50.5 34.5 29.6 45.5 19.6 51.3 27.8 23.  10.4  8.8
 28.8 14.3 51.4 32.9 44.9  9.4 46.4 28.5  0.3 22.8 24.1 37.3 15.9 20.4
 31.7 32.3 11.8 26.3 46.  15.8 25.2 10.8 43.9 42.4 14.6 34.2 29.2 38.2
 60.4 34.  22.2 16.9 17.9 18.9 18.2 27.3 38.3 24.6 25.3 46.9 21.2  7.9
 58.7 44.7 15.  39.8 12.2 27.5 42.  36.1 22.1 13.9 43.   8.6 20.  30.
 10.5 49.4 47.9 32.  63.6 12.7 57.4 16.7 24.3 46.5 20.1 51.2  2.6 50.3
 21.8 35.7  9.6 14.4 46.6 22.9  2.4  6.9 19.2  5.7  3.5 17.2 27.1 70.9
 17.8 24.2 40.3 16.5  2.1 40.6 57.1 31.  11.4 37.  38.1 13.3 34.8 48.8
 22.3 12.8 50.6 44.6 48.3 39.  11.9  2.3 14.8 37.4 39.4 53.8 18.5  9.
 35.5 17.1 45.3  6.7 28.  18.6 45.6 37.8 26.9 38.5 41.3 40.1  8.2 37.1
 34.6 56.7  9.5 42.6 49.7 10.6 46.7 30.5 39.9 40.7 57.6 47.1 57.  46.2
 54.2 47.4 64.2 45.2 10.2 48.1 16.  28.3 42.1 14.2 47.8 15.5 47.7 55.2
 44.1 13.7 33.8 12.5  1.4  3.7 36.3  5.5 43.1 51.5 43.4 52.1 36.  45.8
 41.6 38.  48.2 45.4 25.6 16.1 50.8 11.3 53.7  6.1  3.1  4.7 18.1 12.9
  2.9 14.  50.  45.9 42.7 29.9  6.6 50.1 17.6 51.9 57.5  5.  17.7 51.6
  8.9 12.3  7.7 32.4 58.4  5.8  1.2  1.5 25.8 42.5 47.  40.4  8.3 47.2
  5.3 28.4  8.   3.3 31.4 52.7 62.5 44.  56.1  7.5 54.   6.3  2.2 41.8
 17.5 63.1 59.  49.2  6.5 56.  51.7  9.9 54.1  8.1 54.7  7.8 43.7  8.4
  4.  46.3 48.5 33.2 49.3 45.  64.4 51.8 56.5 13.4  3.  55.5 62.   6.4
  0.8 69.4 56.8 60.  11.   6.  57.3  4.5 44.3 50.9 52.9  0.7 45.1  9.7
 52.3 46.1 57.8 51.1 65.   2.8 53.5  9.8  7.1 59.2 55.6 52.6  3.8 52.5
  9.2  0.2 50.2  2.5  9.1 55.9  2.7 11.7  4.4 11.1  6.2 49.1 59.4  5.1
  2.  48.4 56.3 49.6 49.  53.9 55.7 54.4 49.5] unique values

discover_weekly_user: [False  True] unique values

top_mood: ['Sleep' 'Workout' 'Sad' 'Energetic' 'Happy' 'Party' 'Chill' 'Focus'] unique values

uses_offline_mode: [False  True] unique values

podcasts_too: [ True False] unique values

In [51]:
df.drop('listener_id' , axis = 1, inplace = True)

In [52]:
df

,age,country,platform,subscription,top_genre,top_artist,daily_listening_minutes,songs_per_day,playlists_count,skip_rate_pct,discover_weekly_user,top_mood,uses_offline_mode,podcasts_too
0,24,Australia,Apple Music,Free,R&B,Kendrick Lamar,191,54,9,39.3,False,Sleep,False,True
1,21,Germany,Spotify,Free,Classical,Drake,249,68,10,18.3,True,Workout,True,True
2,32,Japan,Amazon Music,Free,Hip-Hop,Olivia Rodrigo,49,11,11,22.7,True,Sad,False,True
3,39,Japan,Apple Music,Free,Pop,Burna Boy,96,22,8,29.4,True,Sad,True,False
4,23,India,Spotify,Family,Country,Olivia Rodrigo,100,24,13,37.7,True,Workout,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,26,France,Spotify,Family,Pop,SZA,197,55,6,15.3,False,Workout,True,False
3996,35,Germany,YouTube Music,Free,Rock,Ariana Grande,320,77,13,9.2,True,Sad,False,True
3997,43,India,Apple Music,Free,Hip-Hop,Dua Lipa,99,38,5,14.0,False,Happy,True,True
3998,26,India,Apple Music,Student,Indie,SZA,76,31,7,36.1,False,Happy,False,False
3999,24,UK,Spotify,Premium,Hip-Hop,Dua Lipa,161,49,9,37.8,True,Workout,False,False

In [53]:
from sklearn.preprocessing import LabelEncoder

In [54]:
label = LabelEncoder()

In [55]:
df.drop('top_artist' , axis = 1, inplace = True)

In [56]:
df

,age,country,platform,subscription,top_genre,daily_listening_minutes,songs_per_day,playlists_count,skip_rate_pct,discover_weekly_user,top_mood,uses_offline_mode,podcasts_too
0,24,Australia,Apple Music,Free,R&B,191,54,9,39.3,False,Sleep,False,True
1,21,Germany,Spotify,Free,Classical,249,68,10,18.3,True,Workout,True,True
2,32,Japan,Amazon Music,Free,Hip-Hop,49,11,11,22.7,True,Sad,False,True
3,39,Japan,Apple Music,Free,Pop,96,22,8,29.4,True,Sad,True,False
4,23,India,Spotify,Family,Country,100,24,13,37.7,True,Workout,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,26,France,Spotify,Family,Pop,197,55,6,15.3,False,Workout,True,False
3996,35,Germany,YouTube Music,Free,Rock,320,77,13,9.2,True,Sad,False,True
3997,43,India,Apple Music,Free,Hip-Hop,99,38,5,14.0,False,Happy,True,True
3998,26,India,Apple Music,Student,Indie,76,31,7,36.1,False,Happy,False,False
3999,24,UK,Spotify,Premium,Hip-Hop,161,49,9,37.8,True,Workout,False,False

In [57]:
X = df.drop('daily_listening_minutes' , axis = 1)
y = df1['daily_listening_minutes']

In [58]:
X

,age,country,platform,subscription,top_genre,songs_per_day,playlists_count,skip_rate_pct,discover_weekly_user,top_mood,uses_offline_mode,podcasts_too
0,24,Australia,Apple Music,Free,R&B,54,9,39.3,False,Sleep,False,True
1,21,Germany,Spotify,Free,Classical,68,10,18.3,True,Workout,True,True
2,32,Japan,Amazon Music,Free,Hip-Hop,11,11,22.7,True,Sad,False,True
3,39,Japan,Apple Music,Free,Pop,22,8,29.4,True,Sad,True,False
4,23,India,Spotify,Family,Country,24,13,37.7,True,Workout,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...
3995,26,France,Spotify,Family,Pop,55,6,15.3,False,Workout,True,False
3996,35,Germany,YouTube Music,Free,Rock,77,13,9.2,True,Sad,False,True
3997,43,India,Apple Music,Free,Hip-Hop,38,5,14.0,False,Happy,True,True
3998,26,India,Apple Music,Student,Indie,31,7,36.1,False,Happy,False,False
3999,24,UK,Spotify,Premium,Hip-Hop,49,9,37.8,True,Workout,False,False

In [60]:
y

0       191
1       249
2        49
3        96
4       100
       ...
3995    197
3996    320
3997     99
3998     76
3999    161
Name: daily_listening_minutes, Length: 4000, dtype: int64

In [61]:
from sklearn.model_selection import train_test_split

In [62]:
X_train,X_test, y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=1)

In [65]:
print(X_train.shape)

(2800, 12)

In [67]:
print(X_test.shape)

(1200, 12)